### ISSUE TITLE
Update fraud proofs specs

### ISSUE THREAD

**Issue by dariolina** [subspace/protocol-specs#29]
- [x] remove bundle equivocation (https://forum.subspace.network/t/whether-bundle-equivocation-fraud-proof-is-necessary/3339/2)
- [x] replace usage of host functions with MMR proofs (https://github.com/subspace/subspace/issues/2652)
- [x] merge invalid XDM with illegal transaction (https://github.com/subspace/subspace/issues/2738)
- [x] add estimated bundle weight (https://github.com/subspace/subspace/issues/2609)
- [x] add handling of non-existent extrinsic index (https://github.com/subspace/subspace/issues/2287)
